
image: node:11-stretch

before_script:
    - node -v && npm -v
    - npm install

cache:
    paths:
        - node_modules

validate:
    script:
        - npm run lint
        - npm run test
        # Validate that a new build was added
        - npm run build
        - git diff
        - >-
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
              echo -e "\e[41mNo build was added. Run 'npm run build && git add --all' and commit & push again.\e[49m";
              exit 1;
          fi;
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/


